export {default as About} from './About';
export {default as Agreement} from './Agreement';
export {default as Articles} from './Articles';
export {default as Chat} from './Chat';
export {default as Components} from './Components';
export {default as Extras} from './Extras';
export {default as Home} from './Home';
export {default as Notifications} from './Notifications';
export {default as NotificationsSettings} from './NotificationsSettings';
export {default as Privacy} from './Privacy';
// export {default as Profile} from './Profile';
export {default as Register} from './Register';
// export {default as Login} from './Login';
export {default as Rental} from './Rental';
export {default as Rentals} from './Rentals';
export {default as Booking} from './Booking';
export {default as Settings} from './Settings';
export {default as Shopping} from './Shopping';
export {default as PlantDetail} from './PlantDetail';
export {default as SearchScreen} from './views/Search';
export {default as Campings} from './Campings';
export {default as Donation} from './Donation';
export {default as AuthLanding} from '../Auth/AuthLanding';
export {default as Signup} from '../Auth/Signup';
export {default as Login} from '../Auth/Login';
export {default as ForgotPassword} from '../Auth/ForgotPassword';
export {default as PostUpload} from '../components/PostUpload';
export {default as ProfileScreen} from './Profile';
export {default as PostsScreen} from './views/Posts/Posts';
export {default as EventsScreen} from './views/Events/Events';
export {default as EventDetailsScreen} from './views/Events/EventDetails';
export {default as OrganizationsScreen} from './views/Organizations';
export {default as ImageDetails} from '../components/ImageDetails';
export {default as Images} from '../components/Images';
export {default as TreeIdentify} from './views/Identify/TreeIdentify';

