//Actions 
const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
const POSTS_STATE_CHANGE = 'POSTS_STATE_CHANGE'
const EVENTS_STATE_CHANGE = 'EVENTS_STATE_CHANGE'
const ORGANIZATIONS_STATE_CHANGE = 'ORGANIZATIONS_STATE_CHANGE'

const USER_DATA_STATE_CHANGE = 'USER_DATA_STATE_CHANGE'
const POSTS_DATA_STATE_CHANGE = 'POSTS_DATA_STATE_CHANGE'
const EVENTS_DATA_STATE_CHANGE = 'EVENTS_DATA_STATE_CHANGE'
const ORGANIZATIONS_DATA_STATE_CHANGE = 'ORGANIZATIONS_DATA_STATE_CHANGE'

const EVENTS_SEARCH_STATE_CHANGE = 'EVENTS_SEARCH_STATE_CHANGE'
const POSTS_SEARCH_STATE_CHANGE = 'POSTS_SEARCH_STATE_CHANGE'
const ORGANIZATIONS_SEARCH_STATE_CHANGE = 'ORGANIZATIONS_SEARCH_STATE_CHANGE'
const TREES_SEARCH_STATE_CHANGE = 'TREES_SEARCH_STATE_CHANGE'
const USERS_SEARCH_STATE_CHANGE = 'USER_SEARCH_STATE_CHANGE'

const HANDLE_EVENT_EDITED = 'HANDLE_EVENT_EDITED'
const HANDLE_POST_EDITED = 'HANDLE_POST_EDITED'

const HANDLE_COMMENT_SHOW = 'HANDLE_COMMENT_SHOW'
const HANDLE_COMMENT_HIDE = 'HANDLE_COMMENT_HIDE'

const HANDLE_COMMENT_DATA_STATE_CHANGE = 'HANDLE_COMMENT_DATA_STATE_CHANGE'
const HANDLE_NEW_COMMENT_DATA_STATE_CHANGE = 'HANDLE_NEW_COMMENT_DATA_STATE_CHANGE'
const HANDLE_COMMENT_REMOVED = 'HANDLE_COMMENT_REMOVED'
const HANDLE_COMMENT_EDITED = 'HANDLE_COMMENT_EDITED'
const HANDLE_COMMENT_DATA_RESET = 'HANDLE_COMMENT_DATA_RESET'

const HANDLE_POST_REMOVE = 'HANDLE_POST_REMOVE'
const HANDLE_EVENT_REMOVE = 'HANDLE_EVENT_REMOVE'

const HANDLE_POST_ADD = 'HANDLE_POST_ADD'
const HANDLE_EVENT_ADD = 'HANDLE_EVENT_ADD'


const CLEAR_DATA = 'CLEAR_DATA'
const CLEAR_USER = 'CLEAR_USER'
const HANDLE_EVENTS_DATA_RESET = 'HANDLE_EVENTS_DATA_RESET'
const HANDLE_POSTS_DATA_RESET = 'HANDLE_POSTS_DATA_RESET'
const HANDLE_ORGANIZATIONS_DATA_RESET = 'HANDLE_ORGANIZATIONS_DATA_RESET'
const LOGOUT = 'LOGOUT'

const LOADING_STATE_CHANGE = 'LOADING_STATE_CHANGE'


const TREES_DATA_STATE_CHANGE = 'TREES_DATA_STATE_CHANGE';
const TREES_DATA_ADD = 'TREES_DATA_ADD';
const TREES_DATA_FETCH_SUCCESS = 'TREES_DATA_FETCH_SUCCESS';
const TREES_DATA_UPDATE = 'TREES_DATA_UPDATE';
const TREES_DATA_DELETE = 'TREES_DATA_DELETE';
const TREES_DATA_RESET = 'TREES_DATA_RESET';


export {
    USER_STATE_CHANGE,
    POSTS_STATE_CHANGE,
    EVENTS_STATE_CHANGE,
    ORGANIZATIONS_STATE_CHANGE,
    USER_DATA_STATE_CHANGE,
    POSTS_DATA_STATE_CHANGE,
    EVENTS_DATA_STATE_CHANGE,
    ORGANIZATIONS_DATA_STATE_CHANGE,
    EVENTS_SEARCH_STATE_CHANGE,
    POSTS_SEARCH_STATE_CHANGE,
    ORGANIZATIONS_SEARCH_STATE_CHANGE,
    TREES_SEARCH_STATE_CHANGE,
    USERS_SEARCH_STATE_CHANGE,
    HANDLE_EVENT_EDITED,
    HANDLE_POST_EDITED,
    HANDLE_COMMENT_SHOW,
    HANDLE_COMMENT_HIDE,
    HANDLE_COMMENT_DATA_STATE_CHANGE,
    HANDLE_NEW_COMMENT_DATA_STATE_CHANGE,
    HANDLE_COMMENT_REMOVED,
    HANDLE_COMMENT_EDITED,
    HANDLE_COMMENT_DATA_RESET,
    HANDLE_POST_REMOVE,
    HANDLE_EVENT_REMOVE,
    HANDLE_POST_ADD,
    HANDLE_EVENT_ADD,
    CLEAR_DATA,
    CLEAR_USER,
    HANDLE_EVENTS_DATA_RESET,
    HANDLE_POSTS_DATA_RESET,
    HANDLE_ORGANIZATIONS_DATA_RESET,
    LOGOUT,
    LOADING_STATE_CHANGE,
    TREES_DATA_STATE_CHANGE,
    TREES_DATA_ADD,
    TREES_DATA_FETCH_SUCCESS,
    TREES_DATA_UPDATE,
    TREES_DATA_DELETE,
    TREES_DATA_RESET
}


